name: Build
on:
  push:
    branches: master
env:
    CGO_ENABLED: 1
jobs:
    release_linux:
        runs-on: ubuntu-latest
        steps:
        - name: Install Golang Toolchain
        uses: actions/setup-go@v2
            with:
            go-version: 1.14
        - name: Clone the repository
        uses: actions/checkout@v2
        - name: Build
        run: go build -v -o elliot main.go
    - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
            name: elliot-linux-amd64.exe
            path: elliot
    release_darwin:
        runs-on: macos-latest
        steps:
        - name: Install Golang Toolchain
          uses: actions/setup-go@v2
            with:
              go-version: 1.14
        - name: Clone the repository
          uses: actions/checkout@v2
        - name: Build
          run: go build -v -o elliot main.go
        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
              name: elliot-darwin-amd64
              path: elliot
    release_nt:
        runs-on: windows-latest
        steps:
        - name: Install Golang Toolchain
          uses: actions/setup-go@v2
            with:
              go-version: 1.14
        - name: Clone the repository
          uses: actions/checkout@v2
        - name: Build
          run: go build -v -o elliot.exe main.go
        - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
            name: elliot-windows-amd64.exe
            path: elliot.exe