name: Build
on: create
env:
    CGO_ENABLED: 1
jobs:
    release_linux:
        runs-on: ubuntu-latest
        steps:
        - name: Install Golang Toolchain
          uses: actions/setup-go@v2
          with:
            go-version: 1.14
        - name: Clone the repository
          uses: actions/checkout@v2
        - name: Cache
          uses: actions/cache@v1
          with:
            path: ~/go/pkg/mod
            key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              go-${{ runner.os }}-
        - name: Build 64bit
          run: go build -v -o dist/elliot-linux-amd64 main.go
          env:
            GOARCH: amd64
        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
            name: elliot-${{ runner.os }}
            path: dist/*
    release_darwin:
        runs-on: macos-latest
        steps:
        - name: Install Golang Toolchain
          uses: actions/setup-go@v2
          with:
            go-version: 1.14
        - name: Clone the repository
          uses: actions/checkout@v2
        - name: Cache
          uses: actions/cache@v1
          with:
            path: ~/go/pkg/mod
            key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              go-${{ runner.os }}-
        - name: Build 64bit
          run: go build -v -o dist/elliot-darwin-amd64 main.go
          env:
            GOARCH: amd64
        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
            name: elliot-${{ runner.os }}
            path: dist/*
    release_nt:
        runs-on: windows-latest
        steps:
        - name: Install Golang Toolchain
          uses: actions/setup-go@v2
          with:
            go-version: 1.14
        - name: Clone the repository
          uses: actions/checkout@v2
        - name: Cache
          uses: actions/cache@v1
          with:
            path: ~/go/pkg/mod
            key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              go-${{ runner.os }}-
        - name: Build 64bit
          run: go build -v -o dist/elliot-windows-amd64.exe main.go
          env:
            GOARCH: amd64
        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
            name: elliot-${{ runner.os }}
            path: dist/*